### ISSUE TITLE
URI:er med fragment

### ISSUE THREAD

**Issue by carwash** [diggsweden/persistent-identifiers-investigation#1]
Hej! Jag ifrågasätter "Rekommendation BI-5 Använd inte URL:er med fragment." då detta är ett känt och på flera håll etablerat mönster för att komma runt [httpRange-14](https://www.w3.org/2001/tag/issues.html#httpRange-14)-frågan.
Om man inte vill hela tiden 303 peka om URI:er för icke-digitala resurser till digitala dokument som beskriver dem, en vanlig lösning är att ge saken och metadatat _nästan_ samma URI, men skilja dem bara på fragmentet. Därmed kan man få datat man vill komma åt, både om saken och dokumentet, med ett och samma anrop. T.ex.
http://example.com/1234 och dokumentet som beskriver den http://example.com/1234#doc
eller tvärtom
http://example.com/1234#it och dokumentet som beskriver den http://example.com/1234
Det är t.ex. så KB gör hos Libris, med …#it för själva saken, och utan för metadatat.

Missförstår mig inte – jag fattar att det är problematiskt med fragment i URI:er, och föreslår inte att vi ska på något vis förespråka dem i rekommendationen. (De passar nog bäst för att skilja mellan olika beståndsdelar i en resurs, snarare än att skilja mellan olika resurser.) Jag vill bara påpeka att de är redan idag vanligt förekommande i befintliga beständiga identifierare hos stora aktörer, och att detta bör nog tas hänsyn till i rekommendationen.

**Comment by salgo60** [comment]
@carwash varför gegga till det med fragment? Jag har nog bara sett RAÄ som gör detta... KB:s länkade data är väl mest en tragedi...

### Reality check

Wikidata har strul med att hantera RAÄs socknar som ni av någon anledning skapat just med fragment till en RDF resurs...
* har inte fungerat bra sedan 2019 och RAÄ fixar det inte på sin sida att dom löses upp sig men det kanske inte är tanken... dock irriterande när alla andra externa identifierare i Wikidata gör det...

* [SPARQL](https://kulturarvsdata.se/resurser/aukt/geo/parish%231003)  där om du klickar på länken inte löses upp till något vettigt....
   * exempel [resurser/aukt/geo/parish#2439](https://kulturarvsdata.se/resurser/aukt/geo/parish%232439) blir i WD  https://kulturarvsdata.se/resurser/aukt/geo/parish%232439 som ger 404
   
   <img width="999" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/8da90b8b-774e-4699-b008-0670d74160ba">   
   
   * kollar man RDF:en den pekar på så är det mer förståligt men summa summarum en icke användarvänlig implementation plus lite konstig vilket urval ni har [länk](https://phabricator.wikimedia.org/T227554#5335573) 
   
   <img width="735" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/9697f8b4-fd19-4b44-884a-2a36fc92c1e1">
   
 * andra RAÄ relaterade saker jag vill se fixade  [skuggbacklog](https://github.com/salgo60/SamlaLibris/issues/10)

----
Misc
* [Nya ID i Libris](https://www.kb.se/samverkan-och-utveckling/nytt-fran-kb/nyheter-samverkan-och-utveckling/2019-06-12-nya-id-i-libris.html)
* projekt [SFS 1999:175](https://github.com/salgo60/LagrummetLight) --> ett nytt Rättsinformationssystem
   *  "[URI-principer](http://dev.lagrummet.se/dokumentation/system/uri-principer.pdf)"
   
   <img width="717" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/6b083b1f-806d-4f02-90a7-e2d295b132f3">   
   
* SND [PID](https://snd.gu.se/sv/hantera-data/fardigstalla-tillgangliggora/PID)
*

**Comment by lokal-profil** [comment]
@carwash Jag kan se din poäng just i relationen _tinget_ _<->beskrivning av tinget_ som ofta har en benägenhet att blandas ihop.

Undrar om du ser några andra relationer som skulle vara nära nog för att försvara att de bara särskiljs med fragment? Speciellt intressant om du har något exempel med mer än två saker som särskiljs via en sådan mekanism (och det är försvarbart).

**Comment by dpriskorn** [comment]
Jag ogillar fragment som särskiljning av resurser. Det är inte bra design i mina ögon. Att flera stora svenska offentliga aktörer designer det ena kassa system efter det andra är inget att pejla efter eller ens bry sig om tänker jag.

**Comment by carwash** [comment]
@lokal-profil @dpriskorn Jag försökte vara tydlig i mitt första inlägg, att jag inte vill förespråka eller ens försvara det som god praxis. Det jag ville påpeka var, att det är trots allt redan vanligt förekommande. Mitt konkreta förslag skulle då kanske vara att (starkt?) deprikera fragment – men jag tror att _förbjuda_ skulle kunna orsaka problem hos befintliga system. Eller kanske inte? Det är kanske lätt att ändra befintliga förekomster?

**Comment by matthiaspalmer** [comment]
@carwash Jag är medveten om existerande praxis att använda fragment i URI:er i vissa lägen för att undvika 303 redirects. (Cool URIs och httpRange-14 frågan,) Som jag skrivit i texten innan BI-5 så finns det dock nackdelar med användning av fragment, framförallt att man tappar en hel del möjligheter i uppslagningsmekanismen. Det är både en stor nackdel att man inte kan använda link headrar, se UM-8 och UM-9, och att man inte kan livscykelhantera enskilda beständiga identifierare.

Observera också att hela specifikationen är upplagd som rekommendationer, man kan förstås ignorera dem. Det är en öppen fråga om hela specifikationen ska ses som just en rekommendation eller om det ska finnas hårdare krav. Hårdare krav blir naturligtvis svåra att se till att de följs.

Det är också en öppen fråga vilken målgrupp hela specifikationen har. Min tanke, och jag tror också byggblock metadatas position är att man tar fram rekommendationer som är väl genomtänkta och som kan vara en utgångspunkt för offentlig sektor så att man inte behöver tänka igenom saker från början i varje läge.

Jag tror det blir en utmärkt fråga för första mötet att ta upp.

**Comment by matthiaspalmer** [comment]
@salgo60 Tack för många bra länkar. Dock skulle jag uppskatta lite mer koncis och fokuserad dialog kring de frågor som tas upp. Det blir svårt att följa annars med för många separata frågor som diskuteras i samma ärende.

**Comment by salgo60** [comment]
@Mathias Förslag ["lev som ni lär"](https://github.com/diggsweden/information-models-investigation) starta publicera user cases med Persistenta identifierare som ni vill lösa

Länkarna var bara att peka på att detta gjorts 100 tals ggr i Sverige och utomlands känns lite som DIGG inte tar höjd för detta utan startar från 0

**Comment by matthiaspalmer** [comment]
@salgo60 Jag tror jag formulerade mig lite för snällt ovan, I detta projekt håller vi oss till ämnet. Detta ärende handlar om URI:er med fragment. Om du vill prata om något annat får du öppna upp ett nytt ärende.

(Förutsatt förståss att det handlar om förbättringar, förändringar eller korrigeringar kring den terminologi och de tekniska mekanismer som föreslås. Allmänna diskussioner och reflektioner om offentlig sektor och tidigare utredningar får tas någon annanstans.)

Dessutom, kommentar i stil med att ChatGPT kan producera en rekommendation om beständiga identifierare indikerar att du inte läst underlaget. 

Härmed kommer jag nu att börja att ta bort / dölja inlägg som inte är tillräckligt "on topic".

**Comment by salgo60** [comment]
helt ok lycka till...

**Comment by marma** [comment]
Jag tänker att fragment i URI:er för länkad data kan fylla samma roll som de gör för HTML, dvs att göra det möjligt att länka in i ett dokument / beskrivning utan att behöva skapa URI-routing för all typ av struktur inom dokumentet. Därmed finns det användning som absolut bör undvikas, exempelvis `https://example.org/user#12345`, men också tillfällen där det kan vara praktiskt, exempelvis `https://example.org/item/12345#page-14`.

Jag tror också att det beror på vad man exponerar. Affärslogik (användare, organisationer, etc.) har förmodligen mindre behov av fragment än exempelvis ingående metadata för ett objekt.

Detta sagt så tycker jag att URI:er utan fragment är en sensible default om man inte är väldigt säker på vad man håller på med.

**Comment by matthiaspalmer** [comment]
Det verkar som vi har konsensus här, undvika fragment URI:er är en bra rekommendation, men inte ett hårt krav för de som vet vad de gör.

**Comment by matthiaspalmer** [comment]
Möte 3 beslöt att BI-5 med BÖR krav är bra med tillhörande förklaring.
