### ISSUE TITLE
Specificera svarsformat vid 300 Multiple Choices

### ISSUE THREAD

**Issue by carwash** [diggsweden/persistent-identifiers-investigation#10]
### Contact Details

marcus.smith@raa.se

### What benefits does the suggestion solve?

Förtydliga ett gränsfall vid långsiktig förvaltning av URI:er.

### Feature suggestion description

Iom rekommendationerna för http-headers och ompekning i UM-5, UM-6, UM-7 m.fl, samt rekommendationen att tillämpa 410-svar för borttagna resurser (UM-10), rekommendationen bör även ta itu med vilka svarsheaders – och ev. innehåll – som ska skickas i fall där en tidigare enhetlig resurs har delats upp och nu motsvarar två eller fler nya resurser. I sådana fall, när den gamla URI:n lösas upp, ska servern svara med ompekningskoden 300 Multiple Choices. Ingen automatisk ompekning är möjlig, eftersom användaren måste välja hur de ska fortsätta från de olika (och för servern lika giltiga) val. Svarskoden 300 Multiple Choices har dock inte fått bred tillämpning, och dess beteende är luddigt beskriven: Vilka headers och innehåll ska finnas med? Hur ska de olika val formateras?
**Rekommendationen bör rekommendera ett konkret beteende på svarformat för sådana fall, i samma stil som övrig conneg i UM-5—7.**

**Comment by lokal-profil** [comment]
Jag reflekterade också över att detta var ett fall som saknades. Utöver den tekniska delen som @carwash beskriver ovan bör en rekommendation kring uppdelning av en tidigare resurs även förtydliga att den gamla identifieraren inte bör användas för en av de resulterande delarna. Det är ett naturligt konsekvens av UM-10 men jag tror att det kan finnas en poäng att vara extra tydlig här då jag ofta tycker mig se att man har brutit ut en del av den företeelse som tidigare beskrevs till en ny identifierare, men behåller den gamla för det man inte bröt ut.

**Comment by matthiaspalmer** [comment]
Bra förslag, har introducerat UM-12 för detta behov. Jag föreslår att vi använder link headern [successor-version](https://www.rfc-editor.org/rfc/rfc5829.html#section-3.6) för att peka ut delar eller sammanslagningar av tinget.

**Comment by matthiaspalmer** [comment]
Möte 3 beslöt att UM-12 med Link rel=successor-version var en bra lösning.
