### ISSUE TITLE
Principer, definitioner och avgränsningar

### ISSUE THREAD

**Issue by manneandersson** [diggsweden/persistent-identifiers-investigation#11]
### Contact Details

manne.andersson@ehalsomyndigheten.se

### What benefits does the suggestion solve?

Det är viktigt att beskriva och tydliggöra vad som avses med beständiga identifierare. Denna specifikation gäller inte alla typer av identifierare och detta behöver tydliggöras. Helt enkelt vad  det är och vad det inte är.

### Feature suggestion description

Jag tror att det är bra att beskriva skillnaden mellan beständiga identifierare och "verksamhetsidentifierare". Med verksamhetsidenitiferare avser jag identifierarare som exemeplvis personnummer, organisationsnummer, tågnummer, GLN-koder, ISBN-koder, osv. Även detta är identifierare men av en annan typ än vad som avses här, ofta krävs en kontext för att förstå identifieraren.

Det skulle också vara bra att tydligt definiera pinciper eller förutsättningar för beständig identifierare. T.ex. detta gäller
- identifierare för maskiner
- kontextoberoende
- för internet
- federerad hantering av identifierare (även om DNS-namn inte är fullständigt federerad)

Vad är skillnaden mellan identifierare och identitet? Är det en skillnad?

### Additional information

En följdfråga till Metadatabyggblocket är, vad gör vi med "verksamhetsidentifierare"? Ska vi ignorera det eller ska vi skapa en vägledningen för hur vi hanterarar dessa också?

**Comment by matthiaspalmer** [comment]
Specifikationen är skriven utifrån perspektivet att verksamhetsidentifierare inte är fokus.

Det finns skrivningar i bakgrunden av motiverande karaktär:
_"För att minimera risken för krockar och behovet av specialutvecklad programvara är det eftersträvansvärt att använda identifierare som fungerar på samma sätt oberoende av vilken domän / vilket sammanhang vi befinner oss i. Detta gör också att man minskar risken för att identifierarna krockar."_

Samt:
_"För att identifieraren ska vara beständig menas att den på ett tydligt och välkänt sätt refererar till samma ting över en längre tid utan att behöva ändras."_

Ett förslag är att lägga in en sektion om avgränsande karaktär i README. Jag la till ett första utkast som lyder:
_"Med beständiga identifierare avser vi identifierare som är globalt unika och har en välkänd uppslagningsprocess. Identifierare som enbart är unika inom ett visst verksamhetssystem eller kräver domänspecifik kunskap för att slå upp är inte fokus i denna specifikation."_
 
Borde man kanske lägga till en liten diskussion i det planerade bakgrundsdokumentet om verksamhetsidentifierare?

**Comment by matthiaspalmer** [comment]
Möte 4 ansåg sektionen med avgränsningar och sektionen med den korta introduktionen på https://github.com/diggsweden/persistent-identifiers-investigation/tree/main samt kort introduktionen är tillräcklig tillsammans med rekommendation 5 om relationen mellan verksamhetsidentifierare och beständiga identifierare.
