### ISSUE TITLE
GUPRI - Globally Unique, Persistent and Resolvable Identifier

### ISSUE THREAD

**Issue by salgo60** [diggsweden/persistent-identifiers-investigation#2]
Ni borde ta upp GUPRI som en bra modell att jobba med PID:ar se [#54](https://github.com/salgo60/DiggUptime/issues/54)

* exempel på dagens galenskap
  * [#87 Länkröta större problem vid regeringsskiften? vem äger problemet?](https://github.com/salgo60/DiggUptime/issues/87)
  * [#1 Domstolsverket vet inte var författningar från nedlagda myndigheter finns](https://github.com/salgo60/LagrummetLight/issues/1)  

* EU löser detta med länkröta med Internet Archive [länk](https://github.com/Riksarkivet/dataplattform/issues/11)
@dpriskorn vet nog mer om detta

**Comment by dpriskorn** [comment]
Svenska förvaltningen är ju typ världskänd för att ha god ordning på alla papper och arkiv med papper.

Sen i 1990 börjar internet och sen dess har det i princip inget varit någon ordning alls.

Vi har om jag förstått rätt redan förlorat det tidiga svenska delen av internet. Det kommer aldrig tillbaka.

Har det utretts vem som har ansvaret för arkivering av svenska delen av internet?

Ukraina lyckades precis med att själva med stöd från internetarkivet och andra att samla in hur många TB av deras internet som helst på rekordtid som går att ladda ner för vem som helst.

Varför är den digitala förmågan hos myndigheterna efter 33 år av internet fortfarande så låg?

Sitter det kvar folk i ledande ställning på alla myndigheter och tänker i gamla spår?

**Comment by salgo60** [comment]
Exempel förstudie
* DS 1998:10 fanns enligt Internet Archive hos regeringen.se 11 oktober 2022 på [www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem](https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem)
  * nu [hittar jag den hos IA](https://web.archive.org/web/20220811093437/https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem)
  * den verkar nu flyttats till [www.regeringen.se/rattsliga-dokument/departementsserien-och-promemorior/1998/01/ds-199810](https://web.archive.org/web/20220701000000*/https://www.regeringen.se/rattsliga-dokument/departementsserien-och-promemorior/1998/01/ds-199810/)
  
<img width="1374" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/4e8848ce-31f4-4ef0-b040-b3b0a8552087">

<img width="1374" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/331618f8-5f0c-4eaf-89e3-2b0589f09744">

*

**Comment by salgo60** [comment]
Förra gången Persistenta identifierar utreddes så verkar man pratat om en centrallösning dvs. skulle troligen "löst" GUPRI :rocket: men ingen leverans skedde [se Riksarkivet/dataplattform/issues/17#](https://github.com/Riksarkivet/dataplattform/issues/17#issuecomment-1576627510)...


* [Slutrapportering av uppdrag om att främja statlga myndugheters arbete med att tillhängliggöra data för vidareutnyttjande](https://riksarkivet.se/media/pdf-filer/slutrapport-regeringsuppdrag-riksarkivet-180627.pdf)

<img width="699" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/b279034f-1230-449e-b200-ee69004b0905">
<img width="699" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/4f85cf1f-5503-4a73-a3a3-f11147a65d6f">
<img width="699" alt="image" src="https://github.com/Riksarkivet/dataplattform/assets/14206509/d564869c-372d-4a0e-8464-17ea46547705">

**Comment by matthiaspalmer** [comment]
Genom att luta oss på URL:er så får vi både "Globally Unique" och "resolvable".
Att gå mot en lösning som purl.org eller handle.net för att hantera persistens har som jag ser det i huvudsak två nackdelar:
1. Man tappar den organisatoriska kopplingen.
2. Man lägger alla ägg i samma korg, handle kostar pengar och purl.org var skakigt under en tid när det fanns ekonomiska problem.

Dvs, jag är inte övertygad att det blir bättre med centralisering för att garantera persistens.

Min ståndpunkt är att inget varar för evigt, att skapa tekniska lösningar för persistens när det inte finns organisationer bakom som stödjer blir inte bra. Det finns en hel del om purl.org länkar som pekar vidare via 303 till döda sidor. Vad hjälper då att identifieraren finns kvar?

**Comment by salgo60** [comment]
### Det är i högsta grad en demokratifråga att saker överlever organisationer

Jag är på väg till en lunch med [projektet Riksdagens Corpus](https://www.umu.se/nyheter/5-miljoner-till-forskning-om-lankad-parlamentariska-data_11678700) deras [GITHUB](https://github.com/welfare-state-analytics/riksdagen-corpus/issues?q=is%3Aissue+)/ deras [PR med test av datakvaliten](https://github.com/welfare-state-analytics/riksdagen-corpus/actions) där dom kommer att producera TEI dokument av Riksdagens historiska dokument med Persistenta identifierare som pekar på Wikidata vem som pratar i Riksdagen...

![image](https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/24ebd0d7-8250-43c9-bf2a-90224e24d7c6)

**Blir galet när historiska dokument har högre Digital kvalitet än det staten producerar 2023....** förklaringen är enkel det krävs digitala kompetenser


**Steg 1 är identifierare** enormt bra om det blir en självklarhet. Idag ser vi att statens dokumenthanteringen är ad hoc / massa silos / massa länkröta och det är verkar vara webadministratörer som flyttar runt websidor [ kommuner](https://github.com/salgo60/Anslagstavla/issues/19) .. 

* fråga [Riksarkivet](https://github.com/Riksarkivet/dataplattform/issues/17) om dom kan plocka fram dokument ur arkiven med en persistent identifierare
 
> 1. Man tappar den organisatoriska kopplingen

<img width="1414" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/292cb086-0a34-481a-a416-6873d8f43467">

[Listan ovan](https://w.wiki/6oLg) är enligt Wikidata svenska myndigheter / förvaltningsmyndigheterna med när dom upphört... dvs. "den organisatoriska kopplingen" måste hanteras även då organisationen upphört....

Min tro jobba strukturerat och själv använd persistenta identifierare:
* [ ] Skapa user cases vad ni skall hantera och inte hantera - förse dom med PID:ar
* [ ] Staten måste ha en dokument livscykel dvs. kunna hantera sina dokument även då organisationer upphört... 
   * variant begränsa projektet till enbart handla om <del>persistenta</del> identifierare
* [ ] Samla på er exempel med problem / lösningar / kostnader ( se nedan SFS 1999:175) idag ligger mycket av detta i textdokument
   * När Verva lades ned skapade deras f.d. medarbetare Peter Krantz en site för att hantera det se [Verva stänger ner, Eutveckling.se tar över](https://larskarlsson.wordpress.com/2008/12/15/verva-stanger-ner-eutvecklingse-tar-over/) - [eutveckling.se](http://eutveckling.se/)
   * Helt galet att en enskild kan lösa detta och inte Staten? 
      * starta med att skapa best practice
      * involvera Riksarkivet i detta borde vara deras ansvar att leverera en bättre produkt....
* [ ] **konkretisera detta med persistenta identifierare vs textsträngar med kostnader** att prata om persistenta identifierare är för abstrakt för GD:ar / politiker / medborgare
    * Att införa Persistenta Identifierare försöker lösa lite samma problem som SFS 1999:725: Förstudien startade 1996 och skapade  [DS 1998:10](https://web.archive.org/web/20220811093437/https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) och pekar där på saker som säkert gäller även dagens gegga... det intressanta här är att man i princip bara **fokuserade på EN dokumenttyp Författningar** som i princip har en unik Identifierare sitt flrfattningsnummer MEN dessa dokument kan inte enkelt hittas/användas...
       * [DS 1998:10](https://web.archive.org/web/20220811093437/https://www.regeringen.se/49bb67/contentassets/32378143627e4b6da8e9e196773bedbe/ett-offentligt-rattsinformationssystem) pekar på
          * minska kostnader för företagens kostnader för regeladministration - **1998 45-60 miljoner per år**
      
      <img width="670" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/5589d1ed-ae42-460f-a3d9-eec8b029ead3">
      
      * spara tid
      
      <img width="657" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/1e5ff723-d200-4245-ae39-b1374de3dacb">      
      
      * Minska kostnader på > 100 miljoner per år bara i abbonemangskostader
      
      <img width="657" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/54ff2070-5104-4758-b48e-42197b414620">
      
      * 3.4 Allmänheten - ökad demokrati och rättssäkerhet
      
      <img width="657" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/060630c5-d259-45d3-9ccd-699fa5c77ae5">

* **SFS 1999:175 har aldrig levererats**  exempel dagens kaos
  * Status idag se [svar Domstolsverket att man inte vet var författningar finns](https://github.com/salgo60/open-data-examples/issues/2#issuecomment-1175362343)
  
  <img width="698" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/3e1715fc-699f-40fd-8b91-27fad65fe5a9">  
  
  
  * [#2 ESamverkan publicerar dokument med referenser till författningar ingen kan hitta](https://github.com/salgo60/LagrummetLight/issues/2)

> 2. Man lägger alla ägg i samma korg, handle kostar pengar och purl.org var skakigt under en tid när det fanns ekonomiska problem.

* Kan inte "ägget vara Riksarkivet" som skall hantera slutet av dokumentationslivcykeln se fråga dom 
* Dagens "hönsgård" där man inte kan hitta gällande version av ett dokument kostar galet med pengar
* SFS 1999:175 pekade i sin förstudie DS 1999:11 att kostnaden

**Comment by matthiaspalmer** [comment]
@salgo60 Jag är ledsen, men trots den omfattande texten och de många länkarna och bilderna kan jag inte utläsa något konkret förslag av det du skrivit. Ärenden som tas upp i detta projekt måste vara tydliga med antingen förslag på förbättringar, förändringar eller korrigeringar kring den terminologi och de tekniska mekanismer som föreslås. Allmänna diskussioner och reflektioner om offentlig sektor och tidigare utredningar får tas någon annanstans.
Därmed stänger jag detta ärende.
