### ISSUE TITLE
Leverabler, tidplan, intressenter för persistenta identifierare

### ISSUE THREAD

**Issue by salgo60** [diggsweden/persistent-identifiers-investigation#22]
[IA](https://web.archive.org/web/20231218091635/https://github.com/diggsweden/persistent-identifiers-investigation/issues/22)
### Contact Details

salgo60@msn.com

### What happened?

Vi på "utsidan" saknar struktur med DIGGs arbete och brist på leveranser för saker som persistenta identifierare... som jag uppfattar är [grunden till bra digitalisering](https://www.go-fair.org/fair-principles/f1-meta-data-assigned-globally-unique-persistent-identifiers/)

Nu ansluter sig statskontoret i denna klagosång med en [myndighetsanalys](https://www.statskontoret.se/om-oss/vara-publikationer/myndighetsanalyser/) 2023-12-01 som enligt mig är en total sågning av DIGGs sätt att arbeta se [rapport](https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf) / [IA](https://web.archive.org/web/20231208232341/https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf)

exempel
* [sid 10](https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf)

<img width="1001" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/ad6fe54b-51d4-491a-862d-5191f8d89a6a">

**Jag vill se att DIGG tar åt sig av kritiken** och arbetar modernt med **detta projekt publika identifierare** som är grunden i ett bra digitalt ekosystem se [FAIRDATA F1](https://www.go-fair.org/fair-principles/f1-meta-data-assigned-globally-unique-persistent-identifiers/) och har 
* publika prioriterade backlogs
* [tydlighet med projektdata](https://github.com/salgo60/DIGG-skuggbacklog/issues/385), [vilka som är med](https://github.com/diggsweden/persistent-identifiers-investigation/issues/19), roller 
* tydliga tidsplaner, ansvar , vem gör vad
* tydliga leverabler med persistenta identifierare och datum kopplade till en utvecklingsmodell med exempelvis user stories och intressenter...
* att detta [finns som Öppna data](https://github.com/salgo60/DIGG-skuggbacklog/issues/385)
  * dvs. lev som ni lär och visa på hur publika unika identifierare skall användas --> ni lär er och kan skapa bättre rekommendationer än att som idag [bygga på RAÄs erfarenhet av dålig design](https://github.com/diggsweden/persistent-identifiers-investigation/issues/13#issuecomment-1725792617)
* tydlighet med vilka kompetenser som behövs av en myndighet/kommun att leverera detta så vi inte 20 år senare saknar leverans som [SFS 1999:175](https://github.com/salgo60/LagrummetLight) och [regeringskansliet tror att lösningen är ett möte till](https://github.com/salgo60/LagrummetLight/issues/5)

### Steps To Reproduce

- vi saknar tydlighet se [Statskontorets myndighetsgenomlysning av DIGG](https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf) där detta "projekt" är ett bra exempel på otydlighet plus massa externa konsulter... och DIGG är tysta

### What did you expect?

Jobbar proffesionellt / förutsägbart och kostnadseffektivt... idag ser jag viss struktur i detta projekt med GITHUB men långt ifrån vad man skall kunna förvänta sig av en digital expertmyndighet... som borde vara ett föredöme för kommuner och myndigheter...
* att kommuner myndigheter aktiveras och ett ekosystem skapas

**Comment by salgo60** [comment]
"Besvaras" i [Google docs](https://docs.google.com/presentation/d/1qCjklRBu4GYTugv77zbsbvovW230OF00DCXHPZzYri8/edit#slide=id.g285d3d17ae7_0_5) med ett frågetecken - tolkar det som "sett men inte förstått" eller "vill inte se hur eländet det är - jag är ju bara konsult/Digg anställd.."

<img width="680" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/46c5dbae-c085-40dd-9de0-a9ee2b14662f">

är rädd att DIGG och detta projekt inte kan ta in den kritik vi ser i  [myndighetsanalys](https://www.statskontoret.se/om-oss/vara-publikationer/myndighetsanalyser/) 2023-12-01 av DIGGs sätt att arbeta se [Myndighetsanalys av Myndigheten för digital förvaltning](https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf) / [IA](https://web.archive.org/web/20231208232341/https://www.statskontoret.se/siteassets/rapporter-pdf/2023/2023_18---utskriftsformat.pdf)
* pratade idag med handläggaren som skapat rapporten och tog upp detta varför denna analys tog så lång tid att göra på en sådan ung myndighet som säger sig vara en digital expertmyndighet... dom borde vara datadrivna och ha allt digitalt --> en knapptryckning för att hitta avvikelser... 
* även att vi vill se öppna data ihop med en myndighetsanalys så saker kan följas upp snabbt och enkelt och enklare att jämföra myndigheter med varandra...
   * jag ser en myndighetsanalys som att Statskontoret ställer tydliga krav på andra myndigheter som borde kunna formuleras som krav i länkade data jmf [DIGG #252](https://github.com/salgo60/DIGG-skuggbacklog/issues/252) / [Riksdagen #150](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/150) / [Riksarkivet #48](https://github.com/salgo60/Svenskaforsamlingar/issues/48)

**Comment by janderssonse** [comment]
Denna issue stängs som delvis off-topic från projektet och på grund av för brett och spretigt input. Dela upp punkter i enskilda issues i framtiden tack, så går det enklare att svara på dem. Ärenden som inte hör till projekten man lägger issues för som t.ex. Allmänna reflektioner om Digg får tas någon annanstans, och likaså ärenden som försöker täcka mer än sin fokus. Kan också tillägga att det här projektet ingår inte i ”Kultur och arbetssätt” utan i BB Metadata inom Ena, Sveriges digitala infrastruktur. Det är inte försenat och processen ligger tillsammans med deltagare i referensgrupp, issues, presentationer och mötesanteckningar på Github.
