### ISSUE TITLE
Arkivutredningen - persistenta identifierare

### ISSUE THREAD

**Issue by salgo60** [diggsweden/persistent-identifiers-investigation#23]
[IA](https://web.archive.org/web/20231222211710/https://github.com/diggsweden/persistent-identifiers-investigation/issues/23)
### Contact Details

salgo60@msn.com

se [chatGPT om hur persistenta identifierare bör stödjas vid arkivering och vara en del av Arkivförordning (1991:446)](https://github.com/salgo60/DiggUptime/issues/70#issuecomment-1586114522)

### What happened?

skall persistenta identifierare fungera så skall dessa vara **persistenta**. De tankar jag ser i detta rep pekar inte på hur det skall ske utan blir lite http tankar med http koder. DIGGs uppgift är att vara en digital expert myndighet och borde vara tydliga med vilka krav persistenta identfierare ställer på arkiv och [arkivutredningen](https://riksarkivet.se/arkivutredningen)

Lyssnar man på [Riksarkivets presentation 30 november 2023](https://youtu.be/AVH3gPwB63M?si=OXzZeh2USDxXcRG-&t=1050) så saknar vi även att dom har en förståelse och en plan för persistenta identifierare....

<img width="957" alt="image" src="https://github.com/diggsweden/persistent-identifiers-investigation/assets/14206509/f33a68fa-01c9-48f4-af6e-4b5c989d43ec">

jag efterlyser att myndigheter som [DIGG jobbar med tydlighet vilka krav dom har på andra organisationer #252](https://github.com/salgo60/DIGG-skuggbacklog/issues/252) som Riksarkivet och [vice versa #48](https://github.com/salgo60/Svenskaforsamlingar/issues/48) --> att ett projekt som detta skall vara tydliga med hur persistenta identifierare skall vara användbara i hela livscykeln av informationen...

### Steps To Reproduce

* status 2023 jun [#17](https://github.com/Riksarkivet/dataplattform/issues/17)

### What did you expect?

* tydlighet
* att persistenta iderntifierare har ett ekosystem som är maskinläsbart och hanterar att det är enkelt att underhålla #20

**Comment by UlrikaDMattsson** [comment]
Riksarkivet har deltagit i referensgruppen. Reflektioner om andra utredningar och myndigheter får tas någon annanstans. Det är regeringen som styr myndigheter, inte andra myndigheter. Ärendet stängs som off-topic.

**Comment by salgo60** [comment]
> Riksarkivet har deltagit i referensgruppen. Reflektioner om andra utredningar och myndigheter får tas någon annanstans. Det är regeringen som styr myndigheter, inte andra myndigheter. Ärendet stängs som off-topic.

ok er slutsats **att persistenta identifierare skall vara persistenta är off-topic** vem äger problemet och skall ta ansvar för detta? Ni måste vara tydliga med vilka [krav/förväntningar ni har på andra myndigheter](https://github.com/salgo60/DIGG-skuggbacklog/issues/252) 

@UlrikaDMattsson  Vad kom ni fram till? ni har denna övning haft en GITHUB yta i några månader och ni har haft minst 5 möten ni måste kunna få Riksarkivet att skriva in i sin **backlog att persistenta identifierare måste stödjas under hela livscykel....och att det är deras ansvar och ingen annans** 

Det jag uppfattar från [Riksarkivets möte 30 nov 2023](https://youtu.be/AVH3gPwB63M?si=OXzZeh2USDxXcRG-&t=1050) är att dom inte förstår [länkade data](https://youtu.be/r_X8eEEj_jI?si=wIbBmvIKhsJhzGC_&t=18) utan pratar format ex. [FormatE](https://riksarkivet.se/formate)

`Som namnet antyder fokuserar FormatE på format. En handling som kodas till ett  format vid en viss tidpunkt ska kunna avkodas och återges med samma innehåll som vid tidpunkten för kodning. `

**det tolkar jag** som att en persistent identifierare som är en textsträng skall kunna återges som en textsträng då den avkodas dvs [strings not things](https://blog.google/products/search/introducing-knowledge-graph-things-not/)

#### Min tro det går för långsamt
kommer ni inte längre på dessa månader så ser vi ett nytt problem modell det vi ser med [SFS 1999:175 Rättsinformationsförordning](https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175/) där efter mer än [20 års projekt](https://github.com/salgo60/LagrummetLight) så blir det [100 länkar](https://lagrummet.se/lagrummet/rattsinformation/myndigheters-foreskrifter) och Regeringskansliet kan inte ens ge oss en haverirapport eller en status utan skall ha [fler möten](https://github.com/salgo60/LagrummetLight/issues/5)

#### det saknas pondus att vara en förändringsledare
se liknande exempel - 
[En granskningsrapport från Riksrevisionen - Digitala tjänster till privatpersoner – stora utvecklingsmöjligheter för statliga myndigheter RiR 2023:6](https://www.riksrevisionen.se/download/18.1a05284c18705c2c0d82b763/1679914467060/RiR_2023_6_rapport.pdf)
 
<img width="666" alt="image" src="https://github.com/salgo60/DIGG-skuggbacklog/assets/14206509/ce194f89-d381-42a1-b95f-4211013232eb">

**Comment by salgo60** [comment]
**Update** Träffade Riksarkivets chefsjurist [Jens Västberg](https://riksarkivet.se/organisation) förra veckan vid en [dragning om GDPR](https://arkivsormland.se/kulturarvsforum-2024/) och frågade om Riksarkivet pratar om att arkiven skall hantera persistenta identifierare men **enl. honom inget som diskuteras**

**Comment by salgo60** [comment]
[#7](https://github.com/salgo60/LagrummetLight/issues/7) [Synpunkter och kommentarer på ett förslag till tillämpning av FGS Arkivredovisning](https://riksarkivet.se/fgs-remiss) (Verksamhetsbaserad) för överlämnande till Riksarkivet
----  

Jag saknar att ni tar höjd för hanteringen av persistenta unika identifierare i material som skall arkiveras hos er

När information ska överlämnas till Riksarkivet för arkivering, är det viktigt att förstå hur hanteringen av persistenta unika identifierare integreras i processen. Persistenta unika identifierare är nyckelelement för att säkerställa att arkiverat material kan återfinnas och användas effektivt över tid.

För det första, det är avgörande att identifierarna är korrekt implementerade och förankrade inom de digitala systemen hos den verksamhet som lämnar över materialet till Riksarkivet. Detta innebär att det digitala materialet ska vara tydligt märkt med dessa identifierare innan överlämnandet.

För det andra, Riksarkivet måste ha kapacitet att hantera och bevara dessa identifierare på ett sätt som säkerställer deras långsiktiga tillgänglighet och integritet. Detta kan innebära att implementera lämpliga metoder och tekniker för att spåra och bevara identifierarna över tiden, även när tekniska plattformar och standarder förändras.

Tidigare diskussioner och studier, såsom den som genomförts av DIGG (Digitaliseringsmyndigheten), har betonat vikten av att säkerställa att persistenta identifierare förblir tillförlitliga och användbara över tid. Det har också framhållits att samarbete och koordinering med Riksarkivet är avgörande för att säkerställa att dessa identifierare integreras effektivt i den övergripande arkiveringsprocessen men idag verkar detta saknas se [diggsweden/persistent-identifiers-investigation #23](https://github.com/diggsweden/persistent-identifiers-investigation/issues/23) 
För att adressera dessa frågor effektivt, är det nödvändigt att Riksarkivet har en tydlig digital strategi som inkluderar riktlinjer och metoder för hantering av persistenta unika identifierare i arkiverat material. Detta kan bidra till att säkerställa att arkiverad information förblir sökbar och användbar på lång sikt, även när tekniska och organisatoriska förutsättningar förändras över tid...... 

Detta har tidigare diskuterats:
1) hos DIGGs studie av persistenta identifierare se fråga om hur dom kan garantera att dessa identifierare är persistenta om inte Riksarkivet involveras [diggsweden/persistent-identifiers-investigation #23](https://github.com/diggsweden/persistent-identifiers-investigation/issues/23)

2) [frågan ställdes 2023-06-05 direkt till Riksarkivet](https://github.com/Riksarkivet/dataplattform/issues/17) hur data stödet med API är idag och det saknades helt 

3) ett försök att skapa ett [Rättsinformationssystem startas 1996](https://github.com/salgo60/LagrummetLight) och ledde till [SFS 1999:175](https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/rattsinformationsforordning-1999175_sfs-1999-175/) men den är inte idag 2024 levererad se fråga [Regeringskansliet 2023-07-01](https://github.com/salgo60/LagrummetLight/issues/5) och där pekar just Domstolsverket att eftersom detta projekt inte levererats så uppfattar dom att [författningar från myndigheter som upphört inte kan hittas](https://github.com/salgo60/LagrummetLight/issues/1#issue-1397317655).... hade Riksarkivet haft en digital strategi för arkiverat material med persistenta identifierare så hade detta inte varit ett problem
* update 2024-maj SFS 1999:175 utreds [Ju2023/02684](https://github.com/salgo60/LagrummetLight/issues/8)
  * galet dålig data att detta [inte kan ses hos Riksdagens Öppna data](https://github.com/salgo60/Wikidata_riksdagen-corpus/issues/71#issuecomment-2132167422)

4) frågan ställdes direkt till Riksarkivets chefsjurist Jens Västberg 2024-jan om detta diskuteras men inget han hört
 
Hälsningar
Magnus Sälgö
0046-735152802

ett mer modernt problem map arkivering är att hantera länkröta hos kommuner, myndigheter... som idag är enormt dvs. att tittar man 2024 på arkiveringsprocessen så skulle detta problem även innefattas se fråga till [Riksarkivet 2022-12-02](https://github.com/Riksarkivet/dataplattform/issues/11) och hur [EU skapat ett web archive](https://op.europa.eu/en/web/euwebarchive)
