### ISSUE TITLE
Tillåt organisationsnamn som domännamn i beständiga identifierare

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/persistent-identifiers-investigation#7]
### What benefits does the suggestion solve?

Många av våra större myndigheter är idag att betrakta som relativt stabila. Det är inte alltid det finns eller ens är lämpligt att centralisera till en central aktör att mynta beständiga identifierare åt andra. (Som t.ex. att lantmäteriet skulle erbjuda geodata.se som en mer beständig plats för en hel grunddatadomän.)    

### Feature suggestion description

Förtydliga att när man myntar beständiga identifierare så är det ok att att använda den egna organisationens domännamn. Dock bör man tänka igenom och avråda så att man inte myntar beständiga identifierare som är hårt knutna till enskilda system.
Man bör också råda organisationer att behålla gamla domännamn iallafall under en övergångsperiod och använda http headrar för att peka ut de nya adresserna.

Om en organisation slutar existera men att det fortfarande finns identifierare som det finns ett intresse att de finns kvar krävs någon form av förvaltning i ett längre perspektiv. Här kan man tänka sig att någon aktör, t.ex. KB eller Riksarkivet, skulle kunna ta på sig ett mer långsiktigt ansvar för att bevara domäner inom offentlig sektor och stå för lämpliga redirects. Ett sådant erbjudande skulle underlättas / möjliggöras om man tidigare valt att följa denna rekommendation om beständiga identifierare.

**Comment by lokal-profil** [comment]
Till den långsiktiga förvaltningen borde man även kunna lägga till en rekommendation om att de äldre adresserna finns med i headern efter migreringen (se UM-8/UM-9). Kanske då med relationen _deprecated_ el dyl. Det säkerställer att man kan spåra ändringarna från båda hållen.

Tanken att en mer central aktör ansvarar för domänen och redirects känns också väldigt vettig, men kanske som en större fråga än bara för persistenta identifierare (säger jag utan att ha undersökt om det alls finns en policy för hur myndighetsdomäner förvaltas efter namnändring/upphörande).

**Comment by matthiaspalmer** [comment]
@lokal-profil det närmaste jag hittar till en deprecated är "predecessor-version" eller möjligen "convertedFrom", men jag är osäker på om semantiken är rätt. Kolla gärna om du hittar något som passar bätttre: https://www.iana.org/assignments/link-relations/link-relations.xhtml

**Comment by lokal-profil** [comment]
@matthiaspalmer `predecessor-version` verkar inte matcha (begränsad till versionshanterade objekt).

Beskrivningen av `convertedFrom` verkar vara rätt relation utifrån den korta beskrivningen `The document linked to [via ref:convertedFrom] was later converted to the document that contains this link relation`. Där hakparanteserna är min tolkning.

Sedan är inte exempelfallet det tydligaste i min mening då det kan tolkas som ett fall där innehållet på resursen har ändrats, men identifieraren har behållits, och man länkar ut med `convertedFrom` till en ny identifierare som nu innehåller originalinnehållet.

Notera att man på https://ietf-tools.github.io/xml2rfc/#section-2.34 frångår en `convertedFrom`-relationen till förmån för `previous` då det inte finns stöd för den i `<link>`-taggen (inte säker på hur relevant det är för oss.

**Comment by lokal-profil** [comment]
> Till den långsiktiga förvaltningen borde man även kunna lägga till en rekommendation om att de äldre adresserna finns med i headern efter migreringen (se UM-8/UM-9). 
> 
Blir mest konkret att ta med i UM-11 Samt möjligen om det blir en ny UM för #10.

**Comment by matthiaspalmer** [comment]
Den ursprungliga frågan om tillåta organisationsnamn diskuterades på referensgruppsmöte 2. Beslutet blev att det ska tillåtas.

**Comment by matthiaspalmer** [comment]
Efter att ha tänkt lite ser jag inte att det behövs mer än UM-10 och UM-11 för att hantera organisationer som slutar existera. Dvs använda status kod 410 för de resurser som försvinner, och status kod 308 för att peka ut de beständiga identifierare som nu är att föredra.

Dvs ser inget behov av en markering av deprecated då det är implicit i båda fallen (308 och 410).

**Comment by matthiaspalmer** [comment]
Möte 3 beslöt att organisationsnamn är tillåtna men att det tas fram en rekommendation som förtydligar alternativen. Se [rekommendation 3](https://github.com/diggsweden/persistent-identifiers-investigation/blob/main/docs/rekommendationer.md#3-alternativ-till-organisationsnamn-i-best%C3%A4ndiga-identifierare).

**Comment by salgo60** [comment]
>> större myndigheter är idag att betrakta som relativt stabila

* [ESV byter namn till Statskontoret](https://github.com/salgo60/SCB-Wikidata/issues/47) och Statskontoret blir del av gamla ESV  1 jan 2026
* DIGG och PTS kommer nu att slås ihop sägs det
* enligt [Wikipedia](https://sv.wikipedia.org/wiki/Sveriges_myndigheter#Det_allm%C3%A4nna_myndighetsregistret) fanns det 1 394 myndigheter 1990 jmf med idag < 456

* DIGG har idag valt att inte ha en tydlig hantering av sina dokument med versionsnummer och unika identifierare --> förhoppningsvis [städar dom upp sin dokumenthantering](https://community.dataportal.se/topic/1047/flyttat-inl%C3%A4gg-om-f%C3%B6reslagen-sammanslagning-digg-och-pts/6?_=1750858314952) och inför beständiga identifierare som inte har organisationsnamn som domännamn....

<img width="1110" alt="Image" src="https://github.com/user-attachments/assets/e8b6ced8-043e-404f-ac87-07a7b86ed5c6" />
