### ISSUE TITLE
Bör rekommendationen innehålla förslag på utseende av URL:er

### ISSUE THREAD

**Issue by matthiaspalmer** [diggsweden/persistent-identifiers-investigation#8]
### Contact Details

matthias@metasolutions.se

### What benefits does the suggestion solve?

Kanske förväntar sig de som läser rekommendationen att det ska finnas ett rekommenderat utseende på URL:er. Samtidigt finns inga hårda krav på att de måste se ut på ett sätt.

### Feature suggestion description

Tillhandahåll förslag på utseende på URL:er, kanske ta inspiration av den guide som givits av REST profilen:
{protokoll}://{domännamn }/{api}/{version}/{resurs}/{identifierare}?{parametrar}

Uppenbarligen kan den inte användas exakt då vi inte rekommenderar att man tar med parametrar.
Kanske man bör tala om för och nackdelar med att använda en specifik subdomän jämfört med att koda in det i pathen.

Att ta upp flera alternativ med en prioritetsordning skulle kunna hjälpa de som behöver vägledning.

**Comment by marma** [comment]
Enligt mig bör man undvika att blanda ihop versionering av identifieraren eller det den identifierar med versionering av vad den (antar jag) levererar för information. Det är ju inte version X av resursen eller version X av API:et som är resultatet utan (igen antar jag) en uppdaterad beskrivning av saken.

Oavsett version på API:et, eller version på dokumentet, så identifieras samma sak på en högre nivå.

**Comment by marma** [comment]
Jag vill också hänvisa till stycket "Praktiska exempel på identifierare och beskrivningar " från Digisams "Vägledning för ett sammanlänkat kulturarv".

https://raa.diva-portal.org/smash/get/diva2:1674706/FULLTEXT01.pdf

**Comment by matthiaspalmer** [comment]
Möte 4 beslutade att rekommendation 1 på sidan https://github.com/diggsweden/persistent-identifiers-investigation/blob/main/docs/rekommendationer.md löser detta ärende.
