### ISSUE TITLE
Ställningstagande ang. icke-URI identifierare

### ISSUE THREAD

**Issue by carwash** [diggsweden/persistent-identifiers-investigation#9]
### Contact Details

marcus.smith@raa.se

### What benefits does the suggestion solve?

Tydligare avgränsning på vad som omfattas, och inte omfattas, av rekommendationens begrepp "beständiga identifierare".

### Feature suggestion description

På referensgruppsmötet 2023-06-13 väcktes frågor om övriga sorters "beständiga identifierare" utöver de upplösbara URI:erna som rekommendationen i huvudsak berör. Exempel på sådana är personnummer, registreringsbeteckning för fordon, lämningsnummer, osv. Diskussionen på mötet lutade åt att dessa är att betrakta som något annat än "beständiga identifierare" i den bemärkelsen som rekommendationen menar. Det funkar på ett annat sätt, och har ett annat syfte. Men rekommendationen bör ta upp sådana identifierare i texten, även om det bara är att förklara varför de inte räknas, och/eller hur de förhåller sig till URI:er.
Ett annat och mindre tydligt fall som inte diskuterades (förutom förbigående i sammanhanget uppslagstjänster) var identifierare som icke-upplösbara URI:er (URN) och digitala identifierare som DOI. I bägge fall finns dessa som primärt digitala identifierare, och i fallet URN kan t.o.m. betraktas som URI, men för lösa upp dem måste man först gå via en upplösningstjänst t.ex. KBs https://urn.kb.se/resolve?urn=… för URN, och https://doi.org/ för DOI.
Rekommendationen bör ta ställning till huruvida sådana digitala identifierare, inte riktigt upplösbara men egentligen ändå upplösbara, ska anses vara giltiga för rekommendationens ändamål. (Troligtvis *inte*… men jag tror att argumentet *för* URN är starkare än för DOI, ur ett LOD-perspektiv.)
**Rekommendationen borde lyfta både fall som "personnummer" och som URN/DOI i texten, och förtydliga huruvida de anser ingå, och varför (eller varför inte).**

**Comment by matthiaspalmer** [comment]
Möte 4 ansåg sektionen med avgränsningar på https://github.com/diggsweden/persistent-identifiers-investigation/tree/main är tillräcklig tillsammans med rekommendation 5 om relationen mellan verksamhetsidentifierare och beständiga identifierare.
